### ISSUE TITLE
Drag & Drop for the cells

### ISSUE THREAD

**Issue by tarzak** [juliancwirko/meteor-s-grid#1]
Hello. Is it possible to do cells draggable? As it made for cells in [gridstack.js](http://troolee.github.io/gridstack.js/#demo)

**Comment by juliancwirko** [comment]
Hi, It is more like CSS grid skeleton. 
It is something like Bootstrap or Foundation grid system.

So you should try to use it with such libraries like: gridster.js, gridstack.js, jquery-ui sortable or any other drag and drop library. I will test it soon with some libraries. I'll keep you posted.

I also want to work on 'masonry layouts'. It could be fun with flexbox. But this is a plan for the near future.

**Comment by juliancwirko** [comment]
Here you have some quick tests: http://sortable-test.s-grid.meteor.com/

It works well with RubaXa Sortable and there is a small issue with handler width in jQuery UI Sortable. But I think it could be adjusted somehow.

**Comment by tarzak** [comment]
Thanks a lot!
