### ISSUE TITLE
Would it be possible to have an optional pxToRem option?

### ISSUE THREAD

**Issue by dan-gamble** [juliancwirko/meteor-s-grid#2]
It's basically like how autoPrefixer works but instead it just converts font-sizings to rem (https://github.com/cuth/postcss-pxtorem)

Would save having to use `rem-calc` on all font-sizing since the compile would take care of that for you instead :)

**Comment by juliancwirko** [comment]
Hey, I agree that sometimes this could be useful feature. But actually it isn't something which s-grid strongly needs. With Meteor it is hard to customize your build plugin. I think we need to wait for a better build plugin customization options in Meteor core. For now it is not worth it ;)

ps. If you want to work with s-grid without Meteor, you can include it in your gulp or grunt workflow as a separate task (you can use: https://github.com/juliancwirko/s-grid-grunt as a starting point).

**Comment by dan-gamble** [comment]
Ah okay that's fine. I'm very new to Meteor so still exploring things and
think I will use this grid system instead of Foundation or Lost. Thanks :)

**Comment by juliancwirko** [comment]
Cool! Glad you like it. 
Lost is very good, I like it, version 6 is now based on postcss, so `pxtorem` could be integrated even simpler. But with Meteor it could be still hard to run it and make the build process customizable. 
I realy like the idea of PostCSS, but in my opinion (for now of course) Stylus is better chooise for Meteor. It is well known and has official Meteor support. We only need better api/configuration options for build process in Meteor.

**Comment by dan-gamble** [comment]
Yea, i like Lost too, prefer it to the grids in Bootstrap / Foundation. I haven't used Stylus yet but it does interest me so this grid system will give me a good base to work from.

Will keep an eye on these projects to see how they evolve :)
