### ISSUE TITLE
Do the grid file come with the meteor download?

### ISSUE THREAD

**Issue by Orbyt** [juliancwirko/meteor-s-grid#3]
The readME on atmosphere says:

Then in your main *.styl file import:

@import 's-grid-settings'
@import 's-grid-functions'
@import 's-grid-classes' // optional - only if you want to use helper classes

**You will find grid files in the standalone npm package: https://www.npmjs.com/package/s-grid**

Im confused...do I also need to download extra files separately via npm to get the grid files? Or are they already included with `meteor add juliancwirko:s-grid`?

**Comment by juliancwirko** [comment]
Hey, s-grid can work as a separate node module, but with Meteor you don't
have to install npm packages by yourself. Meteor package is all you need.

2015-05-24 8:32 GMT+02:00 Orbyt notifications@github.com:
