### ISSUE TITLE
flex center on small breakpoint

### ISSUE THREAD

**Issue by saschalichtenstein** [juliancwirko/meteor-s-grid#6]
hi,

i have following breakpoints defined "xs: 0" and "s:480px" for example. i have created an center cell and everything works well until the viewport size is goin below 480px. than the element is not longer center it is goin to top. i had this issue with own created classes as well as with the helper classes. thanks in advance.

**Comment by juliancwirko** [comment]
Hi, thanks for reporting this. I will look into it asap.

**Comment by saschalichtenstein** [comment]
ok. but after testing for one day i can say: VERY POWERFUL TOOL!

**Comment by saschalichtenstein** [comment]
saw that my issue should be related to the stylus s-grid

**Comment by juliancwirko** [comment]
Hey, could you prepare a repo for debugging this? Or maybe you could paste here your .html and .styl code? Thanks.

**Comment by saschalichtenstein** [comment]
Sorry for delay, here is my STYLUS code:

section
&nbsp;max-width 980px
&nbsp;padding 0 rem-calc(20)
&nbsp;grid()
&nbsp;&.full
&nbsp;&nbsp;&nbsp;min-height 100vh
.navigation
&nbsp;&nbsp;cell(1, 1, 'center')

and JADE:

nav
&nbsp;section
&nbsp;&nbsp;.navigation
&nbsp;&nbsp;&nbsp;&nbsp;ul
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;li
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a(href="#start") Link1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;li
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a(href="#contact") Link2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;li
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a(href="#blabla") Link3

alongside i use rupture, jeet gs, nib

**Comment by saschalichtenstein** [comment]
hey i think i got some code bugs and started from scratch. now everything seems to work fine. even with smaller breakpoints.

**Comment by juliancwirko** [comment]
Yeah, I couldn't find a bug with code you provided :) I'm glad you figured it out.
